import { YoutubeTranscript } from 'youtube-transcript';
import * as fs from 'fs';
import * as path from 'path';

const GROQ_KEYS = [
  process.env.GROQ_API_KEY_1,
  process.env.GROQ_API_KEY_2,
  process.env.GROQ_API_KEY_3,
  process.env.GROQ_API_KEY_4,
  process.env.GROQ_API_KEY_5,
  process.env.GROQ_API_KEY_6,
  process.env.GROQ_API_KEY_7,
  process.env.GROQ_API_KEY_8,
  process.env.GROQ_API_KEY_9,
  process.env.GROQ_API_KEY_10,
  process.env.GROQ_API_KEY_11
].filter(Boolean) as string[];

// Fallback if no keys are in env
if (GROQ_KEYS.length === 0) {
  console.warn('[GroqService] No GROQ_API_KEYs found in environment variables!');
}

let currentKeyIndex = 0;

export interface GroqKnotResult {
  junctions: { start_ms: number; end_ms: number; reason: string }[];
  sections: { start_ms: number; title: string }[];
  lyrics?: string;
  summary?: string;
  vibe_check?: string;
}

/**
 * Sanitize and validate junctions from LLM output.
 * Fixes: overlaps, out-of-bounds, floating point errors, tiny knots.
 */
function sanitizeJunctions(
  junctions: { start_ms: number; end_ms: number; reason?: string }[],
  durationMs?: number
): { start_ms: number; end_ms: number; reason?: string }[] {
  if (!junctions || junctions.length === 0) return [];

  let cleaned = junctions
    .map(j => ({
      ...j,
      start_ms: Math.round(j.start_ms),
      end_ms: Math.round(j.end_ms),
    }))
    // Clamp end_ms to song duration if known
    .map(j => ({
      ...j,
      start_ms: Math.max(0, j.start_ms),
      end_ms: durationMs ? Math.min(j.end_ms, durationMs) : j.end_ms,
    }))
    // Remove invalid knots (end <= start, or too tiny < 500ms)
    .filter(j => j.end_ms > j.start_ms && (j.end_ms - j.start_ms) >= 500)
    // Sort by start time
    .sort((a, b) => a.start_ms - b.start_ms);

  // Merge overlapping knots
  if (cleaned.length <= 1) return cleaned;
  
  const merged: typeof cleaned = [cleaned[0]];
  for (let i = 1; i < cleaned.length; i++) {
    const prev = merged[merged.length - 1];
    const curr = cleaned[i];
    
    // If current overlaps or is adjacent (within 500ms gap) to previous, merge
    if (curr.start_ms <= prev.end_ms + 500) {
      prev.end_ms = Math.max(prev.end_ms, curr.end_ms);
      prev.reason = prev.reason || curr.reason; // keep first reason
    } else {
      merged.push(curr);
    }
  }

  console.log(`[GroqSanitize] ${junctions.length} raw -> ${merged.length} clean junctions`);
  return merged;
}

export class GroqService {
  /**
   * Load Balancer: Get the next API key in a round-robin fashion
   */
  private static getNextKey(): string {
    const key = GROQ_KEYS[currentKeyIndex];
    currentKeyIndex = (currentKeyIndex + 1) % GROQ_KEYS.length;
    return key;
  }

  /**
   * Ultra-Fast Analysis using Groq + Transcripts
   */
  static async analyzeWithTranscript(youtubeId: string): Promise<GroqKnotResult> {
    console.log(`[Groq] Fetching transcript for ${youtubeId}...`);
    
    let transcriptData;
    let transcriptText = '';

    // Method 1: Try youtube-transcript library
    try {
      transcriptData = await YoutubeTranscript.fetchTranscript(youtubeId);
      transcriptText = transcriptData
        .map(t => `[${Math.round(t.offset * 1000)}ms] ${t.text}`)
        .join('\n');
      console.log(`[Groq] ✅ Transcript fetched via youtube-transcript library`);
    } catch (e) {
      console.warn(`[Groq] Primary transcript fetch failed: ${(e as Error).message}`);
    }

    // Method 2: Try Piped API
    if (!transcriptText) {
      try {
        console.log(`[Groq] Trying Piped API fallback...`);
        const res = await fetch(`https://pipedapi.kavin.rocks/streams/${youtubeId}`);
        if (res.ok) {
          const data = await res.json();
          const subtitles = data.subtitles || [];
          const track = subtitles.find((t: any) => t.code === 'en' || t.autoGenerated) || subtitles[0];
          if (track?.url) {
            const transcriptRes = await fetch(track.url);
            const vttText = await transcriptRes.text();
            // Simple VTT parsing with timestamps
            transcriptText = vttText
              .split('\n\n')
              .slice(1)
              .map(block => {
                const lines = block.split('\n');
                if (lines.length >= 2) {
                  const timeMatch = lines[0].match(/(\d{2}:\d{2}:\d{2}.\d{3}) -->/);
                  if (timeMatch) {
                    const [h, m, s] = timeMatch[1].split(':');
                    const ms = (parseInt(h) * 3600 + parseInt(m) * 60 + parseFloat(s)) * 1000;
                    return `[${Math.round(ms)}ms] ${lines.slice(1).join(' ')}`;
                  }
                }
                return '';
              })
              .filter(Boolean)
              .join('\n');
            console.log(`[Groq] ✅ Transcript fetched via Piped API`);
          }
        }
      } catch (mirrorErr) {
        console.warn(`[Groq] Piped API fallback failed: ${(mirrorErr as Error).message}`);
      }
    }

    // Method 3: Try Invidious API
    if (!transcriptText) {
      try {
        console.log(`[Groq] Trying Invidious API fallback...`);
        const res = await fetch(`https://invidious.jing.rocks/api/v1/captions/${youtubeId}?label=English`);
        if (res.ok) {
          const captions = await res.json();
          if (captions.captions && captions.captions.length > 0) {
            const track = captions.captions.find((t: any) => t.label.includes('English')) || captions.captions[0];
            if (track?.url) {
              const transcriptRes = await fetch(track.url);
              const captionData = await transcriptRes.json();
              if (captionData.lines) {
                transcriptText = captionData.lines
                  .map((l: any) => `[${Math.round(l.start_ms)}ms] ${l.text}`)
                  .join('\n');
                console.log(`[Groq] ✅ Transcript fetched via Invidious API`);
              }
            }
          }
        }
      } catch (invErr) {
        console.warn(`[Groq] Invidious API fallback failed: ${(invErr as Error).message}`);
      }
    }

    // Method 4: Try direct YouTube API with innertube
    if (!transcriptText) {
      try {
        console.log(`[Groq] Trying direct YouTube innertube API...`);
        const res = await fetch(`https://www.youtube.com/watch?v=${youtubeId}`);
        const html = await res.text();
        
        // Extract caption tracks from page HTML
        const captionMatch = html.match(/"captionTracks":\[(.*?)\]/);
        if (captionMatch) {
          const tracks = JSON.parse(`[${captionMatch[1]}]`);
          const track = tracks.find((t: any) => t.languageCode === 'en') || tracks[0];
          if (track?.baseUrl) {
            const transcriptRes = await fetch(track.baseUrl);
            const xmlText = await transcriptRes.text();
            // Parse XML captions with 'start' attribute (in seconds)
            const textMatches = xmlText.matchAll(/<text start="([\d.]+)"[^>]*>(.*?)<\/text>/g);
            transcriptText = Array.from(textMatches)
              .map(m => `[${Math.round(parseFloat(m[1]) * 1000)}ms] ${m[2].replace(/&amp;/g, '&').replace(/&quot;/g, '"').replace(/&#39;/g, "'")}`)
              .join('\n');
            console.log(`[Groq] ✅ Transcript fetched via YouTube innertube`);
          }
        }
      } catch (innertubeErr) {
        console.warn(`[Groq] YouTube innertube fallback failed: ${(innertubeErr as Error).message}`);
      }
    }

    if (!transcriptText) {
      throw new Error('No transcript available for this video (All 4 methods failed).');
    }

    // Save for user inspection
    try {
      const logDir = path.join(process.cwd(), 'logs');
      if (!fs.existsSync(logDir)) fs.mkdirSync(logDir);
      fs.writeFileSync(path.join(logDir, 'latest_transcript.txt'), transcriptText);
      console.log(`[Groq] Transcript saved to logs/latest_transcript.txt`);
    } catch (e) {
      console.warn('[Groq] Failed to save transcript file.');
    }

    const activeKey = this.getNextKey();
    console.log(`[Groq] Using API Key Index: ${currentKeyIndex - 1} (Load Balanced)`);

    const systemPrompt = `
      You are the "Knot" AI Music Editor.
      
      RULES:
      1. SECTIONS: Only include meaningful, sustained lyrical stanzas. NEVER include [संगीत] or [प्रशंसा] in the 'sections' array.
      2. FRAGMENTS: If a tiny phrase (1-3 words) appears and is followed by a long instrumental gap (> 5s), it is an "Intro Fragment" or "Ad-lib"—KNOT it and do NOT make it a section.
      3. KNOT all instrumental gaps > 4 seconds.
      4. Use RAW transcript timestamps.
      5. Output VALID JSON only.

      JSON STRUCTURE:
      {
        "junctions": [{"start_ms": number, "end_ms": number, "reason": "string"}],
        "sections": [{"start_ms": number, "title": "string", "lyrics": "string"}],
        "summary": "string",
        "vibe_check": "string"
      }
    `;

    const userPrompt = `Transcript:\n${transcriptText.slice(0, 32000)}`;

    try {
      const response = await fetch('https://api.groq.com/openai/v1/chat/completions', {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${activeKey}`,
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({
          model: 'llama-3.3-70b-versatile',
          messages: [
            { role: 'system', content: systemPrompt },
            { role: 'user', content: userPrompt }
          ],
          response_format: { type: 'json_object' }
        })
      });

      if (!response.ok) {
        const err = await response.text();
        throw new Error(`Groq API Error: ${err}`);
      }

      const data = await response.json();
      const result = JSON.parse(data.choices[0].message.content);

      // --- POST-PROCESSING (Bulletproof Math) ---
      
      // 1. Apply 1s Buffer to all sections
      if (result.sections) {
        result.sections = result.sections.map((s: any) => ({
          ...s,
          start_ms: Math.max(0, s.start_ms - 1000)
        }));
      }

      // 2. Ensure Intro Knot (0 to first section)
      if (result.sections && result.sections.length > 0) {
        const firstStart = result.sections[0].start_ms;
        if (firstStart > 5000) { // If intro is > 5s
          result.junctions = [
            { start_ms: 0, end_ms: firstStart, reason: "Aggressive Intro Knot" },
            ...(result.junctions || [])
          ];
        }
      }

      // Save for user analysis
      try {
        fs.writeFileSync(path.join(process.cwd(), 'logs', 'latest_knots.json'), JSON.stringify(result, null, 2));
      } catch (e) {}
      
      console.log(`[Groq] Instant analysis complete for ${youtubeId}`);
      return result;
    } catch (error) {
      console.error(`[Groq] Request failed:`, error);
      throw error;
    }
  }

  /**
   * Client-Provided Transcript Analysis (The "Courier" Method)
   */
  static async analyzeClientTranscript(transcriptText: string, youtubeId: string): Promise<GroqKnotResult> {
    console.log(`[Groq] Analyzing client-provided transcript for ${youtubeId}...`);
    
    const activeKey = this.getNextKey();
    const systemPrompt = `
      You are the "Knot" AI Music Editor. Your job is to analyze a timestamped transcript and identify "Lyrical Stanzas" to KEEP and "Boring/Non-Lyrical Parts" to KNOT (skip).

      STRATEGY:
      1. Identify ONLY the stanzas with lyrics.
      2. Intro (0ms to first lyric) is ALWAYS a KNOT.
      3. Outro (last lyric to end) is ALWAYS a KNOT.
      4. Instrumental breaks > 5s are KNOTS.

      OUTPUT ONLY VALID JSON:
      {
        "junctions": [{"start_ms": number, "end_ms": number, "reason": "string"}],
        "sections": [{"start_ms": number, "title": "string", "lyrics": "string"}],
        "summary": "string",
        "vibe_check": "string"
      }
    `;

    const response = await fetch('https://api.groq.com/openai/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${activeKey}`,
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        model: 'llama-3.3-70b-versatile',
        messages: [
          { role: 'system', content: systemPrompt },
          { role: 'user', content: `YouTube ID: ${youtubeId}\nTranscript:\n${transcriptText.slice(0, 32000)}` }
        ],
        response_format: { type: 'json_object' },
        temperature: 0.1
      })
    });

    if (!response.ok) throw new Error(`Groq Error: ${await response.text()}`);
    const data = await response.json();
    return JSON.parse(data.choices[0].message.content);
  }
}
